In [11]:
import numpy as np

In [12]:
arr = np.array([
    [1,2,3],
    [4,3,6],
    [7,8,1]
])
determinant = np.linalg.det(arr)
print(round(determinant))

64


In [9]:
arr = np.array(
    [
        [1,2],
        [3,4]
    ]
)
print(np.linalg.inv(arr))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
M = np.array(
    [
        [1,2],
        [2,4]
    ]
)

print("Matrix: ",M)
R = np.linalg.matrix_rank(M)
print("Rank: ",R)

Matrix:  [[1 2]
 [2 5]]
Rank:  2


In [15]:
A = np.array(
    [
        [3,1],
        [1,2]
    ]
)
B = np.array(
    [9,8]
)
X = np.linalg.solve(A,B)
print(X)

[2. 3.]


In [23]:
import sympy as sp
mat=sp.Matrix([[8,-8,-2],[4,-3,-2],[3,-4,1]])
print(mat)
eigen=mat.eigenvects()
for i in range(3):
    print("Eigen Value :",eigen[i][0])
    print("Eigen Vector :\n",eigen[i][2])

Matrix([[8, -8, -2], [4, -3, -2], [3, -4, 1]])
Eigen Value : 1
Eigen Vector :
 [Matrix([
[  2],
[3/2],
[  1]])]
Eigen Value : 2
Eigen Vector :
 [Matrix([
[3],
[2],
[1]])]
Eigen Value : 3
Eigen Vector :
 [Matrix([
[2],
[1],
[1]])]


In [22]:
arr = np.array([[8,-8,-2],[4,-3,-2],[3,-4,1]])
eigenvalues, eigenvectors = np.linalg.eig(arr)
print(eigenvalues)
print(eigenvectors)

[1. 3. 2.]
[[-0.74278135 -0.81649658 -0.80178373]
 [-0.55708601 -0.40824829 -0.53452248]
 [-0.37139068 -0.40824829 -0.26726124]]


In [1]:
import numpy as np

In [13]:
arr = np.array(
    [
        [1,1,1],
        [0,2,1],
        [-4,4,3]
    ]
)
eigval, eigvec = np.linalg.eig(arr)
print(eigval)
print(eigvec)
Q = eigvec.T
P = np.array([[-1/2,-1,1],[1,1,0],[1,1,1]]).T
Pinv = np.linalg.inv(P)
print(Pinv@arr@P)


[3. 2. 1.]
[[ 5.77350269e-01 -7.07106781e-01  3.33333333e-01]
 [ 5.77350269e-01 -7.07106781e-01  6.66666667e-01]
 [ 5.77350269e-01 -2.36493141e-15 -6.66666667e-01]]
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [53]:
import sympy as sp
import numpy as np
A = sp.Matrix(
    [
        [1,1,1],
        [0,2,1],
        [-4,4,3]
    ]
)
eigen = A.eigenvects()
A = np.array(A)
print("Matrix\n",A)
P = np.zeros((3,3))
for  i in range(len(eigen)):
    print("EigenValues =",eigen[i][0])
    print("Eigenvectors =",eigen[i][2][0])
    P[i] = np.array(list(eigen[i][2][0].reshape(3,1)))
P = P.T
print("Modal Matrix\n",P)
Pinv = np.linalg.inv(P)
print("Inverse of Modal Matrix\n",Pinv)
diagonal_matrix = (Pinv.dot(A).dot(P)).astype(float)
print("Diagonal Matrix\n",diagonal_matrix)


Matrix
 [[1 1 1]
 [0 2 1]
 [-4 4 3]]
EigenValues = 1
Eigenvectors = Matrix([[-1/2], [-1], [1]])
EigenValues = 2
Eigenvectors = Matrix([[1], [1], [0]])
EigenValues = 3
Eigenvectors = Matrix([[1], [1], [1]])
Modal Matrix
 [[-0.5  1.   1. ]
 [-1.   1.   1. ]
 [ 1.   0.   1. ]]
Inverse of Modal Matrix
 [[ 2. -2. -0.]
 [ 4. -3. -1.]
 [-2.  2.  1.]]
Diagonal Matrix
 [[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


[(1, 1, [Matrix([
[-1/2],
[  -1],
[   1]])]), (2, 1, [Matrix([
[1],
[1],
[0]])]), (3, 1, [Matrix([
[1],
[1],
[1]])])]
