In [2]:
import numpy as np
import sympy as sp

In [5]:
arr  = np.array([
    [1,2],
    [3,4]
])



In [24]:
A=sp.Matrix([[1,1,1],[0,2,1],[-4,4,3]])
eign = A.eigenvects()

A = np.array(A).astype(float)
B = np.array(list(map(lambda x: np.array(x[2][0]).reshape(3,),eign)))
P = B.astype(float).T
Pinv = np.linalg.inv(P)
D = Pinv @ A @ P
print(D)
print(P @ D @ Pinv)

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[[ 1.  1.  1.]
 [ 0.  2.  1.]
 [-4.  4.  3.]]


In [29]:
from scipy.linalg import svd

arr = np.array(
    [
        [2,3],
        [3,4],
        [4,5]
    ]
)

U, s, VT = svd(arr)
print(U, s, VT)

[[-0.40505655  0.81808467  0.40824829]
 [-0.56280062  0.12879749 -0.81649658]
 [-0.72054469 -0.56048968  0.40824829]] [8.88391679 0.27572182] [[-0.60566683 -0.79571835]
 [-0.79571835  0.60566683]]
