## OLD

In [2]:
import numpy as np

arr = np.array([2,3,4,5,6,7,8])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[2,3,5]])
arrnames = np.array(['harry','jack','rose','lily'])

print(arr2[arrnames == 'jack' ])



[[4 5 6]]


In [32]:
import numpy as np

arr = np.array([2,3,4,5,6,7,8])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[2,3,5]])
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3.T,"\n",arr3)

print(arr3.T @ arr3)



[[1 4 7]
 [2 5 8]
 [3 6 9]] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


In [5]:
import numpy as np

arr1 = np.array([[1, 2, 3],[2,3,4]])

arr2 = np.array([[4, 5, 6],[3,4,5]])

arr = np.concatenate((arr1, arr2))
ju
print(np.where(arr2[0]==5))

(array([1]),)


In [8]:
import numpy as np

arr1 = np.array([[1, 4, 3],[2,5,4]])

arr2 = np.array([[4, 5, 6],[3,4,5]])

print(np.sort(arr1))

[[1 3 4]
 [2 4 5]]


## 26/04/2023

In [22]:
import numpy as np

points = np.arange(0,1,0.25)
print(np.meshgrid(points,points))
np.savez("testarray",points,points)

[array([[0.  , 0.25, 0.5 , 0.75],
       [0.  , 0.25, 0.5 , 0.75],
       [0.  , 0.25, 0.5 , 0.75],
       [0.  , 0.25, 0.5 , 0.75]]), array([[0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25, 0.25],
       [0.5 , 0.5 , 0.5 , 0.5 ],
       [0.75, 0.75, 0.75, 0.75]])]
