In [2]:
import re


In [24]:
p1 = r"\bgr.{3}"
text = "gray, grey, gr-y, gr!y, gry"
matches = re.findall(p1,text)

print(matches)

['gray,', 'grey,', 'gr-y,', 'gr!y,']


In [35]:
p1 = r"\b[bB]\w+ | \b\w+at"
text = "The cat in the hat sat bat on the ball flat mat."
matches = re.findall(p1,text)

print(matches)

[' cat', ' hat', ' sat', ' bat', 'ball ', ' mat']


In [16]:
text = "My email is john@example.com ram1...234@hotmail.in . Please send me an email at john.doe123@mail.com"
p = r"\b[\w.]+@\w+.\w{2,}"
re.findall(p,text)

['john@example.com', 'ram1...234@hotmail.in', 'john.doe123@mail.com']

In [45]:
text = "Check out my website at http://www.eample.com https://www.example.com . You can also visit https://www.google.com to search the web."
p = r"http[s]?://w{0,3}?[.]\w+[.]\w{2,} | \w*[.]?\w+[.]\w{2,}"
re.findall(p,text)

['http://www.eample.com ',
 'https://www.example.com ',
 'https://www.google.com ']

In [8]:
text = "Check out my website at http://www.eample.com https://www.example.com . You can also visit https://www.google.com to search the web."
p = r"You"

(re.search(p,text))

TypeError: 're.Match' object is not iterable

In [4]:
import pandas as pd



In [2]:
df = pd.DataFrame({
    'name':[1,2,3,4],
    'address':[1,2,3,4]
    })
print(df)

   name  address
0     1        1
1     2        2
2     3        3
3     4        4


In [10]:
data = {
    '2022-01-01': [5, 7, 5],
    '2022-01-02': [7, 5, 6],
    '2022-01-03': [7, 4, 4],
    '2022-01-04': [7, 2, 10]
}
pd.DataFrame(
    [(k, val) for k, vals in data.items() for val in vals], 
    columns=['Date', 'Interviewed']
)
# print([(k, val) for k, vals in data.items() for val in vals])


Date Interviewed
0  2022-01-01   [5, 7, 5]
1  2022-01-02   [7, 5, 6]
2  2022-01-03   [7, 4, 4]
3  2022-01-04  [7, 2, 10]

In [2]:
data = [('a',2),('b',3)]

for key,value in data:
    print(key,value)
    
print([(k, val) for k, vals in data for val in vals])

a 2
b 3


TypeError: 'int' object is not iterable

In [14]:
arr = [['Harry', 37.21], ['Berry', 37.21], ['Tina', 37.2], ['Akriti', 41],['Akriti', 41] , ['Harsh', 39], ['Harsh', 39]]
arr = sorted(arr,key = lambda x:x[1])

l = len(arr)-1
while(arr[l][1] == arr[l-1][1]):
    l-=1
print(arr[l-1])
    
    

['Harsh', 39]


In [14]:
import math

def primefac(n):
    l = []
    for i in range(2, int(math.sqrt(n)) + 1):
        first_time = True
        while n % i == 0:
            if first_time:
                l.append(i)
                first_time = False
            n = n / i
    if n > 2:
        l.append(int(n))
    return l
print(*primefac(315))

3 5 7


In [39]:

import re
passw = "input()nn$12"

if re.search(r"^.{6,15}$",passw) and re.search("\d",passw) and re.search("[*@$]",passw) and re.search(""):
    print("valid")
else:
    print("invalid")

valid


In [50]:
# s = input("Enter a string: ") 
s = "ac...a"
alpha = []
for i in range(97,123):
    alpha.append(chr(i)) 
    for c in alpha: 
        new = s.replace('.',c) 
    if new==new[::-1]:
        print(new) 
        break
else:
    print("Not possible to make the string as palindrome")

acccca


In [ ]:
def printSpiralMat(mat):
    k,count = len(mat[0]),0
    length = a*a
    isCol = True
    r,c = 0,0
    while(count<length):
        

        


In [1]:
import numpy as np
A = np.linspace(0,3,3)
print(A)

[0.  1.5 3. ]


In [37]:
A = np.random.normal(4,4,(3,))
print(np.eye(3,dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [44]:
A = [
    [
        [1,2,3],
        [2,3,4]
    ]
]



A = np.array(A)

print(A)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 2) + inhomogeneous part.