In [2]:
import pandas as pd
import numpy as np

In [5]:
# 1
arr = np.random.randint(0,100,(10,5))
print(arr)

[[21 90 59 16 12]
 [95 11 39 88 67]
 [18 21 90 41 55]
 [61  6 54 16 90]
 [25 76 89 56 38]
 [58 73 88 34 80]
 [91 58 20 96 95]
 [87  8 79 89 40]
 [40 17 70 89 49]
 [99 25 76 73 49]]


In [13]:
# 2
(pd.DataFrame(arr.T).describe(percentiles=[]))

0     1         2          3          4          5          6  \
count   5.000000   5.0   5.00000   5.000000   5.000000   5.000000   5.000000   
mean   39.600000  60.0  45.00000  45.400000  56.800000  66.600000  72.000000   
std    33.842281  35.0  29.35132  34.362771  26.319195  21.302582  33.037857   
min    12.000000  11.0  18.00000   6.000000  25.000000  34.000000  20.000000   
50%    21.000000  67.0  41.00000  54.000000  56.000000  73.000000  91.000000   
max    90.000000  95.0  90.00000  90.000000  89.000000  88.000000  96.000000   

               7          8         9  
count   5.000000   5.000000   5.00000  
mean   60.600000  53.000000  64.40000  
std    35.472525  27.685736  28.26305  
min     8.000000  17.000000  25.00000  
50%    79.000000  49.000000  73.00000  
max    89.000000  89.000000  99.00000

In [15]:
# 3
sumarr = np.array(list(map(np.sum,arr.T)))
print(sumarr)

[595 385 664 598 575]


In [25]:
# 4
arr = np.zeros((4,4),dtype=np.int32)
arr[1:3,1:3] = 1
print(arr)


[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


In [63]:
# 5
rand = np.random.RandomState(23423343)
names = ["Nita","Vinya","Suresh","Rohith","Neerja"]
ages = rand.randint(12,25,len(names))
math_data = rand.randint(60,95,len(names))
math_data = math_data.astype(dtype=np.float32)
hobbies = rand.choice(["Reading","Gaming","Cycling"],len(names))
rollno = np.arange(0,len(names))
rollno = rollno.astype(np.str_)
# rollno[:] = "22BD1A05" + rollno[:]
rollno = np.array(list(map(lambda x: "22BD1A050" + x,rollno)))
print(rollno)
df = pd.DataFrame({
    "name":names,
    "age":ages,
    "hobby":hobbies,
    # "math":math_data
},index=rollno)

# print(df.shape)
# print(df["name"])
# print(df.columns)
print(pd.DataFrame({"name":df["name"],"age":df["age"]}))
df["math"] = math_data
print(np.mean(df["age"]))
print(df[df["age"]>18])
df2 = (df.sort_values(by="age"))
print(df2)

base_cities = ["Mumbai","Agra","Hyderabad"]

city = rand.choice(base_cities,len(names))
df["city"] = city
print(df)
d = {}
# def fun(i):
#     global d, df
#     d[i] = df[df["math"==i]]["math"]
# map(fun,base_cities)
for i in base_cities:
    print(i)
    d[i] = df[df["city"]==i]["math"].mean()

print(d)
    

df

['22BD1A0500' '22BD1A0501' '22BD1A0502' '22BD1A0503' '22BD1A0504']
              name  age
22BD1A0500    Nita   18
22BD1A0501   Vinya   18
22BD1A0502  Suresh   12
22BD1A0503  Rohith   15
22BD1A0504  Neerja   22
17.0
              name  age    hobby  math
22BD1A0504  Neerja   22  Reading  60.0
              name  age    hobby  math
22BD1A0502  Suresh   12   Gaming  77.0
22BD1A0503  Rohith   15  Cycling  70.0
22BD1A0500    Nita   18  Cycling  74.0
22BD1A0501   Vinya   18   Gaming  62.0
22BD1A0504  Neerja   22  Reading  60.0
              name  age    hobby  math       city
22BD1A0500    Nita   18  Cycling  74.0       Agra
22BD1A0501   Vinya   18   Gaming  62.0  Hyderabad
22BD1A0502  Suresh   12   Gaming  77.0     Mumbai
22BD1A0503  Rohith   15  Cycling  70.0     Mumbai
22BD1A0504  Neerja   22  Reading  60.0       Agra
Mumbai
Agra
Hyderabad
{'Mumbai': 73.5, 'Agra': 67.0, 'Hyderabad': 62.0}


name  age    hobby  math       city
22BD1A0500    Nita   18  Cycling  74.0       Agra
22BD1A0501   Vinya   18   Gaming  62.0  Hyderabad
22BD1A0502  Suresh   12   Gaming  77.0     Mumbai
22BD1A0503  Rohith   15  Cycling  70.0     Mumbai
22BD1A0504  Neerja   22  Reading  60.0       Agra

In [77]:
# 6
rand2 = np.random.RandomState(232324321)
names = ["ram","ashok","priya","chetan","rishika"]
df = pd.DataFrame({
    "name":names
})
subs = ["python","java","c","c++"]

for i in subs:
    df[i] = rand2.randint(60,100,len(names))
print(df["python"].mean())
print(df.loc[2][df.columns!="name"].sum())
print((df.loc[3][df.columns!="name"].sum()/(100*len(subs)))*100)
print(df[df[df.columns!="names"]])


df


73.8
304
73.75


ValueError: Boolean array expected for the condition, not object