In [5]:
import numpy as np
import time

In [24]:
print(time.perf_counter())

1628.8892988


In [15]:
arr = np.array([[(100*j)+i for i in range(100)] for j in range(100)])
print(arr)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
