In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr.ndim)

1


In [52]:
np.random.seed(0)
a = np.random.randint(10,size = 6)
print(a.astype('float64').itemsize)

8


In [53]:
a = np.array([[100 for _ in range(10)] for _ in range(4)])

print(a)

[[100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]]


In [65]:
def middlesquare(arr):
    m,n = arr.shape[0], arr.shape[1]
    return arr[m//2 - 1:m//2+1, n//2-1 : n//2+1]
    


In [55]:
a1 = np.random.randint(100,size=(10,3,6))
print(a1.dtype)
print(a1.ndim)
print(a1.itemsize)
print(a1.nbytes)

int32
3
4
720


In [56]:
a2 = np.random.randint(100,size=(6,100,300))
print(a1.dtype)
print(a1.ndim)
print(a1.itemsize)
print(a1.nbytes)

int32
3
4
720


In [57]:
a3 = np.random.randint(100,size=(400,300,800))
print(a3.dtype)
print(a3.ndim)
print(a3.itemsize)
print(a3.nbytes)
arr.shape

int32
3
4
384000000


(5,)

In [3]:
a4 = np.random.randint(100,size=(4,4))
print(a4.dtype)
print(a4.ndim)
print(a4.itemsize)
print(a4.nbytes)
print(a4)
print(a4[1:3,1:3])
print(middlesquare(a4))

int32
2
4
64
[[69 47 39 43]
 [53  6 97  2]
 [96 88 79 85]
 [45  3 38 95]]
[[ 6 97]
 [88 79]]


NameError: name 'middlesquare' is not defined

In [5]:
print(a4.size)

16


In [10]:
arr = np.array(['a','b','c','d','e','f','g','h','i','j','k','l','m','n'])
arr.itemsize

4